language: node_js
sudo: false
dist: trusty
node_js: stable
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm i -g bower
- npm i
- bower install
- ./node_modules/selenium-standalone/bin/selenium-standalone install
- ./node_modules/selenium-standalone/bin/selenium-standalone start &
script:
- ./node_modules/.bin/wdio wdio.conf.js 
